# Configuration for Docker Hub (Library)
[[registry]]
prefix = "docker.io"
location = "docker.io"

# Configuration for Google Container Registry
[[registry]]
prefix = "gcr.io"
location = "gcr.io"

# Configuration for Google Artifact Registry
[[registry]]
prefix = "pkg.dev"
location = "pkg.dev"
