#!/bin/bash

source $(dirname "$0")/colors
CPU_USAGE=$(mpstat 1 1 | awk '/Average/{ printf "%.0f", 100-$NF }')

if [[ $CPU_USAGE -ge 90 ]]; then
	echo -e "\uF0E4 $CPU_USAGE%\n"
	echo -e "$RED\n"
elif [[ $CPU_USAGE -ge 50 ]]; then
	echo -e "\uF0E4 $CPU_USAGE%\n"
	echo -e "$YELLOW\n"
else
	echo -e "\uF0E4 $CPU_USAGE%\n"
	echo -e "$GREEN\n"
fi
