#!/bin/bash

source $(dirname "$0")/colors

DISK_MAIN=$(df -h | grep "dm-0")
DISK_PERC=$(echo $DISK_MAIN | awk '{ printf "%0.f", $5 }')
DISK_SIZE=$(echo $DISK_MAIN | awk '{ print $2 }')
DISK_USE=$(echo $DISK_MAIN | awk '{ print $3 }')

if [[ $DISK_PERC -ge 90 ]]; then
	echo -e "\uf0c7 $DISK_USE / $DISK_SIZE\n"
	echo -e "$RED\n"
elif [[ $DISK_PERC -ge 70 ]]; then
	echo -e "\uf0c7 $DISK_USE / $DISK_SIZE\n"
	echo -e "$YELLOW\n"
else
	echo -e "\uf0c7 $DISK_USE / $DISK_SIZE\n"
	echo -e "$GREEN\n"
fi
