#!/bin/sh

B='#00000000' # blank
C='#00000000' # clear ish
D='#A5A2A2FF' # default
T='#A5A2A2FF' # text
W='#DB2D20FF' # wrong
V='#FDED02FF' # verifying

i3lock \
  --insidevercolor=$C \
  --ringvercolor=$V \
  --insidewrongcolor=$C \
  --ringwrongcolor=$W \
  --insidecolor=$B \
  --ringcolor=$D \
  --linecolor=$B \
  --separatorcolor=$D \
  --textcolor=$T \
  --timecolor=$T \
  --datecolor=$T \
  --keyhlcolor=$W \
  --bshlcolor=$W \
  --screen \
  0 \
  --blur \
  5 \
  --clock \
  --indicator \
  --timestr="%H:%M:%S" \
  --datestr="%A, %m %Y"

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
