#!/bin/bash

RED="#CD3F45"
GREEN="#9FCA56"
YELLOW="#E6CD69"
BLUE="#55B5DB"
MAGENTA="#A074C4"
CYAN="#55DBBE"
WHITE="#D6D6D6"
BLACK="#151718"

_ok() {
	printf "\e[32m${1}\e[0m\n"
}

_bad() {
	printf "\e[31m${1}\e[0m\n"
}
