#!/bin/bash

source $(dirname "$0")/colors
RAM_USAGE=$(free -h | awk '/Mem/{print $3 }')
RAM_CAPACITY=$(free -h | awk '/Mem/{ print $2 }')
RAM_PERC=$(free | awk '/Mem/{print $3/$2 * 100.0}' | cut -d"." -f1)

if [[ $RAM_PERC -ge 90 ]]; then
	echo -e "\uF080 $RAM_USAGE / $RAM_CAPACITY\n"
	echo -e "$RED\n"
elif [[ $RAM_PERC -ge 50 ]]; then
	echo -e "\uF080 $RAM_USAGE / $RAM_CAPACITY\n"
	echo -e "$YELLOW\n"
else
	echo -e "\uF080 $RAM_USAGE / $RAM_CAPACITY\n"
	echo -e "$GREEN\n"
fi
