#!/usr/bin/bash -x

enter_tracklist () {
  new_songs=$(mpc playlist -f '%title%\t%time%' | awk -F'\t' -vOFS='\t' '{sub(":","\t",$2)}1' | tr '\n' '\t')
  new_vinyl=$(mpc playlist -f '%title%\t%time%\t' | awk -F'\t' -vOFS='\t' '{sub(":","\t",$2)}1' | tr '\n' '\t')
  edit_songs=$(mpc playlist -f '%title%\t%time%\t\t' | awk -F'\t' -vOFS='\t' '{sub(":","\t",$2)}1' | tr '\n' '\t')
  edit_vinyl=$(mpc playlist -f '%title%\t%time%\t\t\t\t\t\t\t\t' | awk -F'\t' -vOFS='\t' '{sub(":","\t",$2)}1' | tr '\n' '\t')
  new_comp=$(mpc playlist -f '%artist%\t\t\t%title%\t%time%' | awk -F'\t' -vOFS='\t' '{sub(":","\t",$5)}1' | tr '\n' '\t')
  mode=$(echo -e "1. Add New Entry\n2. Edit Existing Entry\n3. Add Compilation\n4. Add Vinyl\n5. Edit Vinyl" | rofi -kb-accept-alt '' -dmenu -p ">  " -width 1000)
  if [[ ${mode} == "1. Add New Entry" ]]
  then
    songs="${new_songs}"
  elif [[ ${mode} == "2. Edit Existing Entry" ]]
  then
    songs="${edit_songs}"
  elif [[ ${mode} == "3. Add Compilation" ]]
  then
    songs="${new_comp}"
  elif [[ ${mode} == "4. Add Vinyl" ]]
  then
    songs="${new_vinyl}"
  elif [[ ${mode} == "5. Edit Vinyl" ]]
  then
    songs="${edit_vinyl}"
  fi
  xdotool type "${songs}"
}

create_forum_post () {
  chromium "https://www.musik-sammler.de/forum/post.php?tid=10092"
  sleep 2
  link=$(xclip -o -selection clipboard)
  html=$(curl -Ss "${link}")
  artist=$(echo "${html}" | pup --charset utf-8 -p 'div[class=grid-container]' | pup --charset utf-8 -p 'span[itemprop="name"]' | sed -n '5 p' | cut -c 2-)
  album=$(echo "${html}" | pup --charset utf-8 -p 'div[class=grid-container]' | pup --charset utf-8 -p 'span[itemprop="name"]' | sed -n '8 p' | cut -c 2-)
  final="[b]${artist} - ${album}[/b]"
  image=$(curl -Ss "${link}" | pup --charset utf-8 -p 'meta[property="og:image"]' | egrep -o 'https?://[^ ]+.jpg')
  image="[img]${image}[/img]"
  echo -e "${final}\n${image}\n${link}" | xclip -selection clipboard
  sleep 0.5;
  xdotool key ctrl+v
}

menu=$(echo -e "1. Tracklist\n2. Create Forum Post\n---\n3. Type current song\n4. Type current album" | rofi -kb-accept-alt '' -width 1000 -dmenu -p ">  ")
val=$?

if [[ $val -eq 1 ]]
then
  exit
fi

if [[ ${menu} == "1. Tracklist" ]]
then
  enter_tracklist
elif [[ ${menu} == "1.1 Edit Tracklist" ]]
then
  edit_tracklist
elif [[ ${menu} == "2. Create Forum Post" ]]
then
  create_forum_post
elif [[ ${menu} == "3. Type current song" ]]
then
  song=$(mpc current -f '##np %artist% - %title%')
  xdotool type "${song}"
elif [[ ${menu} == "4. Type current album" ]]
then
  album=$(mpc current -f '##np "%album%" album von %albumartist%')
  xdotool type "${album}"
fi



