#!/bin/bash
#
# rofi-systemdialog - systemdialog with rofi (wayland-ready)
#
# Copyright (c) 2018 by Christian Rebischke <chris@nullday.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http: #www.gnu.org/licenses/
#
#======================================================================
# Author: Christian Rebischke
# Email : chris@nullday.de
# Github: www.github.com/shibumi

_rofi() {
  rofi -i -no-levenshtein-sort -lines 8 "$@"
}

input=$(echo "lock|quit sway|reboot|poweroff" | _rofi -sep '|' -dmenu -p "systemdialog:")

case $input in
  "lock")
    swaylock
    ;;

  "quit sway")
    case $(echo "yes|no" | _rofi -sep '|' -dmenu -p "do you really want to quit:") in
      "yes")
        sway-msg exit
        ;;
      "no") ;;

    esac
    ;;

  "reboot")
    case $(echo "yes|no" | _rofi -sep '|' -dmenu -p "do you really want to reboot:") in
      "yes")
        systemctl reboot
        ;;
      "no") ;;

    esac
    ;;

  "poweroff")
    case $(echo "yes|no" | _rofi -sep '|' -dmenu -p "do you really want to poweroff:") in
      "yes")
        systemctl poweroff
        ;;
      "no") ;;

    esac
    ;;
esac

# vim: :set et sw=2 ts=2 tw=80:
