#!/bin/bash
# vim:set et sw=4 ts=4 tw=72:

intel=$(swaymsg -t get_workspaces)
declare -a workspaces=('一' '二' '三' '四' '五' '六' '七' '八' '九' '十')

for i in "${workspaces[@]}"; do
  if ! echo "$intel" | grep $i; then
    swaymsg "move container to workspace $i"
    exit 0
  fi
done
