#!/bin/bash

source $(dirname "$0")/colors

if systemctl status "wg-quick@germany.service" >/dev/null; then
  echo -e "\uF023 VPN (Germany)\n"
  echo -e "$GREEN\n"
elif systemctl status "wg-quick@singapore.service" >/dev/null; then
  echo -e "\uF023 VPN (Singapur)\n"
  echo -e "$GREEN\n"
else
  echo -e "\uF023 VPN\n"
  echo -e "$RED\n"
fi
