#!/bin/bash

source $(dirname "$0")/colors
ACPI_B_MAIN=$(acpi -b)
BAT_STATE=$(echo $ACPI_B_MAIN | awk '{print $3}')
BAT_PERC=$(echo $ACPI_B_MAIN | awk '{printf "%d", $4}')
BAT_REMAINING=$(echo $ACPI_B_MAIN | awk '{print $5}')

if [[ $BAT_STATE == "Discharging," ]]; then
    if [[ $BAT_PERC -ge 50 ]]; then
        echo -e "\uf241 ($BAT_PERC% : $BAT_REMAINING)\n"
        echo -e "$GREEN\n"
    elif [[ $BAT_PERC -ge 20 ]]; then
        echo -e "\uf242 ($BAT_PERC% : $BAT_REMAINING)\n"
        echo -e "$GREEN\n"
    elif [[ $BAT_PERC -ge 10 ]]; then
        echo -e "\uf243 ($BAT_PERC% : $BAT_REMAINING)\n"
        echo -e "$YELLOW\n"
    else
        echo -e "\uf244 ($BAT_PERC% : $BAT_REMAINING)\n"
        echo -e "$RED\n"
        notify-send -t 3000 -u critical "Battery" "Very low"
    fi
else
    echo -e "\uF240 $BAT_PERC%\n"
    echo -e "$GREEN\n"
fi
